/** Generated by `scripts/build.ts`: every file under `pages/`, lazily imported. */
declare module "virtual:pages" {
  import type { Component } from "vue";

  export const pages: Record<string, () => Promise<{ default: Component }>>;
}

declare module "*.vue" {
  import type { DefineComponent } from "vue";

  const component: DefineComponent;
  export default component;
}
