/** Generated by `scripts/build.ts`: every file under `pages/`, lazily imported. */
declare module "virtual:pages" {
  import type { Component } from "svelte";

  export const pages: Record<string, () => Promise<{ default: Component; layout?: Component }>>;
}
