// Generated by `bunyad types:generate`. Do not edit; run it again after changing routes, pages, or shared props.

const routes = {
  "appearance.edit": "/settings/appearance",
  "dashboard": "/dashboard",
  "home": "/",
  "login": "/login",
  "login.store": "/login",
  "logout": "/logout",
  "password.confirm": "/confirm-password",
  "password.confirm.store": "/confirm-password",
  "password.edit": "/settings/password",
  "password.email": "/forgot-password",
  "password.request": "/forgot-password",
  "password.reset": "/reset-password/{token}",
  "password.store": "/reset-password",
  "password.update": "/settings/password",
  "profile.destroy": "/settings/profile",
  "profile.edit": "/settings/profile",
  "profile.update": "/settings/profile",
  "register": "/register",
  "register.store": "/register",
  "two-factor.confirm": "/settings/two-factor/confirm",
  "two-factor.disable": "/settings/two-factor",
  "two-factor.enable": "/settings/two-factor",
  "two-factor.login": "/two-factor-challenge",
  "two-factor.login.store": "/two-factor-challenge",
  "two-factor.recovery-codes": "/settings/two-factor/recovery-codes",
  "two-factor.show": "/settings/two-factor",
  "verification.notice": "/email/verify",
  "verification.send": "/email/verification-notification",
  "verification.verify": "/email/verify/{id}/{hash}",
} as const;

export type RouteName = keyof typeof routes;

type Segment = string | number;
/** `/users/{user}/posts/{post?}` → `{ user: Segment; post?: Segment }`. */
type ParamsOf<Uri extends string> = Uri extends `${string}{${infer Param}}${infer Rest}`
  ? (Param extends `${infer Name}?` ? { [K in Name]?: Segment } : { [K in Param]: Segment }) & ParamsOf<Rest>
  : unknown;
type Query = Record<string, Segment | boolean | null | undefined>;
type Args<N extends RouteName> = {} extends ParamsOf<(typeof routes)[N]>
  ? [params?: ParamsOf<(typeof routes)[N]> & Query]
  : [params: ParamsOf<(typeof routes)[N]> & Query];

/**
 * The URL of a named route: `route("dashboard")`, `route("password.reset", { token })`.
 * Other params become the query string.
 */
export function route<N extends RouteName>(name: N, ...[params]: Args<N>): string {
  let uri: string = routes[name];
  const query = new URLSearchParams();
  for (const [key, value] of Object.entries(params ?? {})) {
    if (value === null || value === undefined) continue;
    const pattern = new RegExp(`\\{${key}\\??\\}`);
    if (pattern.test(uri)) uri = uri.replace(pattern, encodeURIComponent(String(value)));
    else query.set(key, String(value));
  }
  // Optional segments left unfilled drop out.
  uri = uri.replace(/\/?\{[^}]+\?\}/g, "") || "/";
  const search = query.toString();
  return search ? `${uri}?${search}` : uri;
}
