// Generated by `bunyad types:generate`. Do not edit; run it again after changing routes, pages, or shared props.

declare module "@bunyad/inertia" {
  /** `Inertia.render(name, props)` is checked against these. */
  interface Pages {
    "auth/confirm-password": {};
    "auth/forgot-password": {};
    "auth/login": {};
    "auth/register": {};
    "auth/reset-password": { token: string; email?: string | undefined };
    "auth/two-factor-challenge": {};
    "auth/verify-email": {};
    "dashboard": {};
    "settings/appearance": {};
    "settings/password": {};
    "settings/profile": { mustVerifyEmail: boolean };
    "settings/two-factor": { enabled: boolean; pending: boolean; qrCodeSvg: string | null; setupKey: string | null; recoveryCodes: Array<string> };
    "welcome": {};
  }
}

export {};
