/** Generated by `scripts/build.ts`: every file under `pages/`, lazily imported. */
declare module "virtual:pages" {
  import type { ComponentType } from "react";

  export const pages: Record<string, () => Promise<{ default: ComponentType }>>;
}
