// Generated by `bunyad types:generate`. Do not edit; run it again after changing routes, pages, or shared props.

/** Props every page gets: `HandleInertiaRequests.share()` and the validation `errors`. */
export type SharedData = { name: string; auth: { user: { id: string | number; name: string; email: string; initials: string } | null }; status: string | null } & { errors: Record<string, string> };
