import { afterAll, beforeAll, describe, expect, test } from "bun:test";
import { schemaFor } from "@bunyad/database";
import { Model, checkModelSchema, generateModelTypes, modelColumnsInterface } from "../src/index.ts";
import { testDrivers, type TestDriver } from "./test-drivers.ts";

const drivers: TestDriver[] = await testDrivers();

class StArticle extends Model {
  static table = "st_articles";
  static fillable = ["title", "body", "views", "meta", "published_at", "price", "is_live"];
  static hidden = ["body"];
  static softDeletes = true;
  static casts() {
    return { meta: "json" as const, published_at: "datetime" as const, price: "decimal:2" as const, is_live: "boolean" as const };
  }
}

describe.each(drivers.map((d) => [d.name, d] as const))(
  "schema types and drift check (%s)",
  (_name, driver) => {
    const c = driver.connection;
    beforeAll(async () => {
      Model.setConnection(c);
      const schema = schemaFor(c);
      await schema.dropIfExists("st_articles");
      await schema.create("st_articles", (t) => {
        t.id();
        t.string("title");
        t.text("body").nullable();
        t.integer("views").default(0);
        t.text("meta").nullable();
        t.timestamp("published_at").nullable();
        t.string("price").nullable();
        t.boolean("is_live").nullable();
        t.string("internal_note").nullable();
        t.timestamps();
        t.softDeletes();
      });
    });
    afterAll(async () => { await schemaFor(c).dropIfExists("st_articles"); });

    test("prints one interface per model with cast-aware, nullability-aware types", async () => {
      const out = await modelColumnsInterface(StArticle);
      expect(out).toContain("export interface StArticleColumns {");
      expect(out).toMatch(/\n  id: number( \| bigint)?;/);
      expect(out).toContain("title: string;");
      expect(out).toContain("body: string | null;");
      expect(out).toContain("views: number;");
      expect(out).toContain("meta: unknown | null;");          // json cast
      expect(out).toContain("published_at: Date | null;");     // datetime cast
      expect(out).toContain("price: string | null;");          // decimal:2 cast
      expect(out).toContain("is_live: boolean | null;");       // boolean cast
      expect(out).toContain("internal_note: string | null;");
    });

    test("the generated file is valid TypeScript", async () => {
      const file = await generateModelTypes([StArticle]);
      expect(file).toContain("// Generated by `bunyad schema:types`");
      const js = new Bun.Transpiler({ loader: "ts" }).transformSync(file);
      expect(typeof js).toBe("string");
    });

    test("a model that matches its table has no errors", async () => {
      const issues = await checkModelSchema(StArticle);
      expect(issues.filter((i) => i.severity === "error")).toEqual([]);
    });

    test("untracked columns are reported as a warning", async () => {
      const issues = await checkModelSchema(StArticle);
      expect(issues.some((i) => i.severity === "warning" && i.message.includes("internal_note"))).toBe(true);
    });

    test("typos and missing columns are errors with a clear message", async () => {
      class Broken extends Model {
        static table = "st_articles";
        static fillable = ["title", "titel"];
        static hidden = ["secret"];
        static casts() { return { vews: "integer" as const }; }
      }
      const messages = (await checkModelSchema(Broken)).filter((i) => i.severity === "error").map((i) => i.message);
      expect(messages).toContain("fillable lists [titel], which is not a column of [st_articles]");
      expect(messages).toContain("hidden lists [secret], which is not a column of [st_articles]");
      expect(messages).toContain("cast for [vews] has no matching column in [st_articles]");
    });

    test("timestamps, soft deletes and the primary key are checked against the table", async () => {
      class NoStamps extends Model {
        static table = "st_articles";
        static primaryKey = "uuid";
        static softDeletes = true;
        static fillable = ["title"];
      }
      const schema = schemaFor(c);
      await schema.dropIfExists("st_plain");
      await schema.create("st_plain", (t) => { t.id(); t.string("title"); });
      class Plain extends Model {
        static table = "st_plain";
        static softDeletes = true;
      }
      const a = (await checkModelSchema(NoStamps)).map((i) => i.message);
      expect(a).toContain("primary key [uuid] is not a column of [st_articles]");
      const b = (await checkModelSchema(Plain)).map((i) => i.message);
      expect(b).toContain("timestamps are on but [st_plain] has no [created_at] column");
      expect(b).toContain("softDeletes is on but [st_plain] has no [deleted_at] column");
      await schema.dropIfExists("st_plain");
    });

    test("a missing table is reported, not thrown", async () => {
      class Ghost extends Model { static table = "st_ghost"; }
      expect(await checkModelSchema(Ghost)).toEqual([{ severity: "error", model: "Ghost", table: "st_ghost", message: "table [st_ghost] does not exist" }]);
      await expect(modelColumnsInterface(Ghost)).rejects.toThrow(/does not exist/);
    });
  },
);
