/**
 * `bunyad types:generate` — TypeScript for the frontend and the server, read
 * from the app itself:
 *
 * - `resources/js/routes.ts`: the named routes and a typed `route()` helper
 * - `resources/js/types/shared.d.ts`: `SharedData`, what `HandleInertiaRequests.share()` returns
 * - `types/inertia.d.ts`: each page's props, so `Inertia.render()` checks names and props
 *
 * Types are printed as plain structures (props are JSON), so neither side
 * imports the other's files: the server's `@/` and the frontend's `@/` differ.
 */
import { existsSync, mkdirSync } from "node:fs";
import { dirname, relative, resolve } from "node:path";
import type * as TS from "typescript";

export type GeneratedFile = { path: string; contents: string };

const HEADER = "// Generated by `bunyad types:generate`. Do not edit; run it again after changing routes, pages, or shared props.\n";

/** The route helper: route names and URIs in, typed `route()` out. */
export function routesModule(routes: Record<string, string>): string {
  const entries = Object.entries(routes)
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([name, uri]) => `  ${JSON.stringify(name)}: ${JSON.stringify(uri)},`)
    .join("\n");
  return `${HEADER}
const routes = {
${entries}
} as const;

export type RouteName = keyof typeof routes;

type Segment = string | number;
/** \`/users/{user}/posts/{post?}\` → \`{ user: Segment; post?: Segment }\`. */
type ParamsOf<Uri extends string> = Uri extends \`\${string}{\${infer Param}}\${infer Rest}\`
  ? (Param extends \`\${infer Name}?\` ? { [K in Name]?: Segment } : { [K in Param]: Segment }) & ParamsOf<Rest>
  : unknown;
type Query = Record<string, Segment | boolean | null | undefined>;
type Args<N extends RouteName> = {} extends ParamsOf<(typeof routes)[N]>
  ? [params?: ParamsOf<(typeof routes)[N]> & Query]
  : [params: ParamsOf<(typeof routes)[N]> & Query];

/**
 * The URL of a named route: \`route("dashboard")\`, \`route("password.reset", { token })\`.
 * Other params become the query string.
 */
export function route<N extends RouteName>(name: N, ...[params]: Args<N>): string {
  let uri: string = routes[name];
  const query = new URLSearchParams();
  for (const [key, value] of Object.entries(params ?? {})) {
    if (value === null || value === undefined) continue;
    const pattern = new RegExp(\`\\\\{\${key}\\\\??\\\\}\`);
    if (pattern.test(uri)) uri = uri.replace(pattern, encodeURIComponent(String(value)));
    else query.set(key, String(value));
  }
  // Optional segments left unfilled drop out.
  uri = uri.replace(/\\/?\\{[^}]+\\?\\}/g, "") || "/";
  const search = query.toString();
  return search ? \`\${uri}?\${search}\` : uri;
}
`;
}

/** Print a type as a plain structure: what JSON would carry to the other side. */
function printer(ts: typeof TS, checker: TS.TypeChecker) {
  const print = (type: TS.Type, depth: number, seen: Set<TS.Type>): string => {
    const flags = type.flags;
    if (flags & (ts.TypeFlags.Any | ts.TypeFlags.Unknown)) return "unknown";
    if (flags & (ts.TypeFlags.StringLike | ts.TypeFlags.NumberLike | ts.TypeFlags.BooleanLike | ts.TypeFlags.Null | ts.TypeFlags.Undefined | ts.TypeFlags.Void)) {
      return checker.typeToString(type);
    }
    if (type.isUnion()) {
      // Values first, then null / undefined, as people write them.
      const parts = [...new Set(type.types.map((member) => print(member, depth, seen)))]
        .sort((a, b) => Number(a === "null" || a === "undefined") - Number(b === "null" || b === "undefined"));
      if (parts.includes("true") && parts.includes("false")) {
        parts.splice(parts.indexOf("true"), 1);
        parts.splice(parts.indexOf("false"), 1, "boolean");
      }
      return parts.join(" | ");
    }
    if (type.isIntersection()) return type.types.map((member) => wrap(print(member, depth, seen))).join(" & ");
    if (checker.isArrayType(type)) return `Array<${print(checker.getTypeArguments(type as TS.TypeReference)[0]!, depth + 1, seen)}>`;
    if (checker.isTupleType(type)) {
      return `[${checker.getTypeArguments(type as TS.TypeReference).map((member) => print(member, depth + 1, seen)).join(", ")}]`;
    }
    // A Date crosses as its JSON string.
    if (type.symbol?.name === "Date") return "string";
    if (!(flags & ts.TypeFlags.Object) || depth > 8 || seen.has(type)) return "unknown";

    const inner = new Set(seen).add(type);
    const members: string[] = [];
    for (const index of checker.getIndexInfosOfType(type)) {
      members.push(`[key: ${checker.typeToString(index.keyType)}]: ${print(index.type, depth + 1, inner)}`);
    }
    for (const property of checker.getPropertiesOfType(type)) {
      const propertyType = checker.getTypeOfSymbol(property);
      // Functions do not survive JSON.
      if (propertyType.getCallSignatures().length > 0 && checker.getPropertiesOfType(propertyType).length === 0) continue;
      const optional = property.flags & ts.SymbolFlags.Optional ? "?" : "";
      const key = /^[A-Za-z_$][\w$]*$/.test(property.name) ? property.name : JSON.stringify(property.name);
      members.push(`${key}${optional}: ${print(propertyType, depth + 1, inner)}`);
    }
    return members.length === 0 ? "{}" : `{ ${members.join("; ")} }`;
  };
  const wrap = (text: string) => (text.includes(" | ") ? `(${text})` : text);
  return (type: TS.Type) => print(type, 0, new Set());
}

function createProgram(ts: typeof TS, tsconfig: string): TS.Program {
  const parsed = ts.getParsedCommandLineOfConfigFile(tsconfig, {}, {
    ...ts.sys,
    onUnRecoverableConfigFileDiagnostic: (diagnostic) => {
      throw new Error(ts.flattenDiagnosticMessageText(diagnostic.messageText, "\n"));
    },
  })!;
  return ts.createProgram({ rootNames: parsed.fileNames, options: parsed.options });
}

/** The default export's symbol, through `export default X` aliases. */
function defaultExport(ts: typeof TS, checker: TS.TypeChecker, file: TS.SourceFile): TS.Symbol | undefined {
  const module = checker.getSymbolAtLocation(file);
  const symbol = module && checker.getExportsOfModule(module).find((entry) => entry.name === "default");
  if (!symbol) return undefined;
  return symbol.flags & ts.SymbolFlags.Alias ? checker.getAliasedSymbol(symbol) : symbol;
}

/** `SharedData` from `HandleInertiaRequests.share()`, plus the `errors` the base class adds. */
function sharedTypes(ts: typeof TS, root: string): string | undefined {
  const middleware = resolve(root, "app/Http/Middleware/HandleInertiaRequests.ts");
  if (!existsSync(middleware) || !existsSync(resolve(root, "tsconfig.json"))) return undefined;
  const program = createProgram(ts, resolve(root, "tsconfig.json"));
  const checker = program.getTypeChecker();
  const file = program.getSourceFile(middleware);
  const cls = file && defaultExport(ts, checker, file);
  const share = cls && checker.getDeclaredTypeOfSymbol(cls).getProperty("share");
  if (!share) return undefined;
  const signature = checker.getTypeOfSymbol(share).getCallSignatures()[0];
  if (!signature) return undefined;
  const shared = checker.getAwaitedType(signature.getReturnType()) ?? signature.getReturnType();
  return `${HEADER}
/** Props every page gets: \`HandleInertiaRequests.share()\` and the validation \`errors\`. */
export type SharedData = ${printer(ts, checker)(shared)} & { errors: Record<string, string> };
`;
}

/** Each page's props, from its default export's first parameter. */
function pageTypes(ts: typeof TS, root: string): string | undefined {
  const pagesDir = resolve(root, "resources/js/pages");
  const tsconfig = resolve(root, "resources/js/tsconfig.json");
  if (!existsSync(pagesDir) || !existsSync(tsconfig)) return undefined;
  const program = createProgram(ts, tsconfig);
  const checker = program.getTypeChecker();
  const print = printer(ts, checker);
  const entries: string[] = [];
  for (const file of program.getSourceFiles()) {
    if (!file.fileName.startsWith(pagesDir + "/") || !/\.tsx?$/.test(file.fileName)) continue;
    const name = relative(pagesDir, file.fileName).replace(/\.tsx?$/, "").replaceAll("\\", "/");
    const component = defaultExport(ts, checker, file);
    if (!component) continue;
    const parameter = checker.getTypeOfSymbol(component).getCallSignatures()[0]?.getParameters()[0];
    const props = parameter ? print(checker.getTypeOfSymbol(parameter)) : "{}";
    entries.push(`    ${JSON.stringify(name)}: ${props};`);
  }
  // Pages written in .vue or .svelte are not read; leave Inertia.render open.
  if (entries.length === 0) return undefined;
  return `${HEADER}
declare module "@bunyad/inertia" {
  /** \`Inertia.render(name, props)\` is checked against these. */
  interface Pages {
${entries.sort().join("\n")}
  }
}

export {};
`;
}

/** Everything `types:generate` writes, for an app at `root` whose named routes are `routes`. */
export async function generateTypes(root: string, routes: Record<string, string>): Promise<GeneratedFile[]> {
  const files: GeneratedFile[] = [];
  if (existsSync(resolve(root, "resources/js"))) {
    files.push({ path: "resources/js/routes.ts", contents: routesModule(routes) });
  }
  const ts = (await import("typescript")).default;
  const shared = sharedTypes(ts, root);
  if (shared) files.push({ path: "resources/js/types/shared.d.ts", contents: shared });
  const pages = pageTypes(ts, root);
  if (pages) files.push({ path: "types/inertia.d.ts", contents: pages });
  return files;
}

/** Write the files that changed; returns the paths written. */
export async function writeGenerated(root: string, files: GeneratedFile[]): Promise<string[]> {
  const written: string[] = [];
  for (const file of files) {
    const target = resolve(root, file.path);
    const current = existsSync(target) ? await Bun.file(target).text() : undefined;
    if (current === file.contents) continue;
    mkdirSync(dirname(target), { recursive: true });
    await Bun.write(target, file.contents);
    written.push(file.path);
  }
  return written;
}
