/**
 * Opinionated default stack — re-exports the packages apps typically need.
 * Apps may still cherry-pick individual `@bunyad/*` packages.
 */

export {
  Application,
  app,
  setApplicationInstance,
  HttpKernel,
  createFetchHandler,
  pathnameOf,
  serve,
  startWorkers,
  shutdownSignal,
  onShutdown,
  requestShutdown,
  installShutdownHandlers,
  resolveAppBasePath,
  isBunEmbeddedPath,
  type Provider,
  type ApplicationOptions,
  type ServeOptions,
  type ServeDevelopment,
  type StartWorkersOptions,
} from "@bunyad/core";

export {
  Container,
  Injectable,
  BindingResolutionError,
  CircularDependencyError,
} from "@bunyad/container";

import {
  Middleware as middlewareDecorator,
  WithoutMiddleware,
  Request,
  FormRequest,
  JsonResource,
  JsonApiResource,
  json,
  redirect,
  to_route,
  Redirector,
  stream,
  streamJson,
  eventStream,
  streamDownload,
  abort,
  abort_if,
  abort_unless,
  response,
  HttpResponse,
  HttpException,
  runPipeline,
  throttle,
  RateLimiter,
  Limit,
  setRateLimiter,
  registerRateLimitPresets,
} from "@bunyad/http";
import type {
  Middleware as MiddlewareType,
  MiddlewareLayer,
  SessionBag,
} from "@bunyad/http";

export {
  Request,
  FormRequest,
  JsonResource,
  JsonApiResource,
  json,
  redirect,
  to_route,
  Redirector,
  stream,
  streamJson,
  eventStream,
  streamDownload,
  abort,
  abort_if,
  abort_unless,
  response,
  HttpResponse,
  HttpResponse as Response,
  HttpException,
  runPipeline,
  throttle,
  RateLimiter,
  Limit,
  setRateLimiter,
  registerRateLimitPresets,
  WithoutMiddleware,
};
export type { MiddlewareLayer, SessionBag };
export type Middleware = MiddlewareType;
export const Middleware = middlewareDecorator;

export {
  Route,
  Router,
  route,
  url,
  asset,
  action,
  Url,
  Uri,
  signed,
  handleUrl,
  runWithUrlContext,
  getUrlContext,
  type UrlFacade,
  type RouteParamValue,
  type UrlDefaults,
} from "@bunyad/router";

export {
  Auth,
  Gate,
  SessionGuard,
  TokenGuard,
  Password,
  PasswordBroker,
  MemoryPasswordTokenRepository,
  DatabasePasswordTokenRepository,
  setAuthGuard,
  getAuthGuard,
  setTokenGuard,
  getTokenGuard,
  setDefaultGuardName,
  getDefaultGuardName,
  setPasswordBroker,
  auth,
  guest,
  can,
  confirmPassword,
  abilities,
  ability,
  markPasswordConfirmed,
  confirmPasswordFor,
  loginThrottleKey,
  loginLimiter,
  registerLoginLimiter,
  redirectGuestsTo,
  redirectUsersTo,
  authorize,
  preventRequestForgery,
  verifyCsrf,
  csrf_token,
  hasValidOrigin,
  appendRememberCookie,
  verified,
  verificationUrl,
  fulfillEmailVerification,
  sendEmailVerificationNotification,
  setEmailVerificationSender,
  MustVerifyEmail,
  isMustVerifyEmail,
  mustVerifyEmailMethods,
  Hash,
  bcrypt,
  HasApiTokens,
  type ApiTokenMethods,
  type HasApiTokensOptions,
  AccessResponse,
  Login,
  Failed,
  Logout,
  Authenticated,
  PasswordConfirmed,
  Registered,
  Verified,
  PasswordReset,
  TwoFactor,
  TwoFactorAuthenticatable,
  setTwoFactorIssuer,
  type TwoFactorAuthenticatableMethods,
  flushAuthExtensions,
  applyAuthConfig,
  setAuthEventDispatcher,
} from "@bunyad/auth";

export {
  Session,
  MemorySessionStore,
  FileSessionStore,
  DatabaseSessionStore,
  RedisSessionStore,
  startSession,
  setSessionStore,
  getSessionStore,
} from "@bunyad/session";

export {
  view,
  render,
  setViewFactory,
  getViewFactory,
  setPreloadedViews,
  ViewFactory,
  Component,
  jsonForHtml,
} from "@bunyad/view";

export {
  Inertia,
  inertia,
  Middleware as InertiaMiddleware,
  handleInertiaRequests,
  LazyProp,
  AlwaysProp,
  OptionalProp,
  DeferProp,
  InertiaResponse,
  ResponseFactory as InertiaResponseFactory,
  configureSsr,
  dispatchSsr,
  type InertiaPage,
  type HandleInertiaRequestsOptions,
  type SharedPropValue,
  type VersionValue,
  type SsrOptions,
  type SsrRenderResult,
  type SsrRenderFn,
  type SsrMode,
} from "@bunyad/inertia";

export {
  Feature,
  FeatureManager,
  FeatureFake,
  ArrayFeatureStore,
  DatabaseFeatureStore,
  ensureFeaturesAreActive,
  getFeatures,
  setFeatures,
  type FeatureStore,
  type FeatureDefinition,
  type FeatureResolver,
  type DatabaseFeatureStoreOptions,
} from "@bunyad/features";

export {
  Metrics,
  Entry as MetricsEntry,
  MetricsManager,
  MemoryMetricsStore,
  RedisMetricsStore,
  RedisMetricsIngest,
  RequestsRecorder,
  ExceptionsRecorder,
  ServersRecorder,
  getMetrics,
  setMetrics,
  aggregateEntries,
  renderMetricsDashboard,
  MetricsController,
  registerMetricsRoutes,
  type AggregateType,
  type MetricsEntryRecord,
  type MetricsValueRecord,
  type MetricsFilter,
  type MetricsStore,
  type MetricsIngest,
  type MetricsAggregateRow,
  type MetricsRoutesOptions,
  type RedisMetricsClient,
  type RequestSample,
  type ServerSample,
} from "@bunyad/metrics";

export {
  Head,
  HeadBuilder,
  HeadManager,
  getHeadManager,
  setHeadManager,
  runWithHead,
  handleHead,
  shareHeadWithInertia,
  type HeadCallback,
  type TitleOptions,
  type CanonicalOptions,
  type OgOptions,
  type OgImageOptions,
  type HeadElement,
  type ResolvedHead,
} from "@bunyad/head";

export {
  OAuth,
  OAuthUser,
  AbstractProvider,
  GithubProvider,
  GoogleProvider,
  DiscordProvider,
  GitlabProvider,
  type OAuthServices,
  type OAuthUserMap,
  type ProviderConfig,
  type ProviderFactory,
  type TokenResponse,
} from "@bunyad/oauth";

export {
  Billing,
  Billable,
  BillableConcern,
  billable,
  Checkout,
  CheckoutBuilder,
  Subscription,
  SubscriptionBuilder,
  StripeClient,
  ArraySubscriptionRepository,
  WebhookController,
  handleStripeWebhook,
  verifyStripeSignature,
  Invoice,
  retrieveStripeInvoice,
  listStripeInvoices,
  type BillableOwner,
  type BillingConfig,
  type SubscriptionAttributes,
  type SubscriptionRepository,
  type FindBillable,
  type StripeWebhookEvent,
  type InvoiceDownloadOptions,
  type StripeInvoice,
} from "@bunyad/billing";

export {
  Search,
  Searchable,
  SearchableConcern,
  searchable,
  Builder as SearchBuilder,
  CollectionEngine,
  AlgoliaEngine,
  MeilisearchEngine,
  searchableUpdate,
  searchableDelete,
  makeAllSearchable,
  removeAllFromSearch,
  type Engine as SearchEngine,
  type SearchDocument,
  type SearchableModel,
  type SearchConfig,
} from "@bunyad/search";


export {
  Model,
  ModelQuery,
  Factory,
  Pivot,
  HasMany,
  HasOne,
  BelongsTo,
  BelongsToMany,
  MorphMany,
  MorphOne,
  MorphTo,
  morphMap,
  clearMorphMap,
  OrmCollection,
  Attribute,
  AsCollection,
  AsFluent,
  AsEnumCollection,
  ModelNotFoundException,
  UseBuilder,
  HasUuids,
  HasUlids,
  HasFactory,
  SoftDeletes,
  Prunable,
  MassPrunable,
  prune,
  pruneAll,
  uuid7,
  ulid,
  type FactoryAttributes,
  type CastType,
  type CastDefinition,
  type EnumCast,
  type ModelBuilderConstructor,
  type ModelQueryOptions,
} from "@bunyad/orm";

export {
  Collection,
  collect,
  Fluent,
  Crypt,
  Str,
  Stringable,
  Arr,
  dataGet,
  dataSet,
  dataFill,
  dataForget,
  BunyadError,
  DdException,
  useDdThrow,
  runWithDdThrow,
  runWithHttpDd,
  ddHtmlPage,
  resolveDumpValues,
  blank,
  filled,
  dump,
  dd,
  tap,
  value,
  withValue,
  when,
  optional,
  throw_if,
  throw_unless,
  retry,
  once,
  flushOnce,
  defer,
  flushDeferred,
  now,
  today,
  env,
  report,
  rescue,
  rescueAsync,
  Pipeline,
  installGlobals as installCommonGlobals,
} from "@bunyad/common";

export {
  validate,
  validator,
  Validator,
  ValidationException,
  setPresenceVerifier,
  getPresenceVerifier,
  presenceVerifierFor,
  type Rules,
  type PresenceVerifier,
  type ValidateOptions,
} from "@bunyad/validation";

export {
  MemoryCacheStore,
  FileCacheStore,
  RedisCacheStore,
  CacheRepository,
  setCache,
  cache,
  Cache,
  CacheFake,
} from "@bunyad/cache";

export {
  Log,
  SingleChannel,
  StackChannel,
  ConsoleChannel,
  setLogChannel,
  getLogChannel,
  type LogLevel,
  type LogChannel,
} from "@bunyad/log";

export {
  Event,
  EventFake,
  Dispatcher,
  setEventDispatcher,
  event,
} from "@bunyad/events";

export {
  Job,
  QueueManager,
  MemoryQueueDriver,
  SyncQueueDriver,
  DatabaseQueueDriver,
  RedisQueueDriver,
  MemoryFailedJobRepository,
  DatabaseFailedJobRepository,
  setQueue,
  dispatch,
  SerializesModels,
  registerSerializableModel,
  Queue,
  QueueFake,
  Bus,
  Batch,
  PendingDispatch,
  PendingChain,
  PendingBatch,
  MemoryBatchRepository,
  DatabaseBatchRepository,
  setBatchRepository,
  getBatchRepository,
  getQueue,
} from "@bunyad/queue";

export {
  Mailable,
  ArrayMailer,
  LogMailer,
  SmtpMailer,
  ResendMailer,
  PostmarkMailer,
  MailgunMailer,
  SesMailer,
  setMailer,
  setMailQueue,
  registerMailable,
  setMailViewRenderer,
  markdownToHtml,
  SEND_QUEUED_MAILABLE,
  Mail,
  MailFake,
} from "@bunyad/mail";

export {
  LocalFilesystem,
  S3Filesystem,
  StorageManager,
  setStorage,
  Storage,
  StorageFake,
} from "@bunyad/filesystem";

export { Image, PendingImage } from "@bunyad/image";
export type {
  EncodeOptions,
  ImageFormat,
  ImageSource,
  ProcessedImage,
  Transform,
  UploadedFile as ImageUploadedFile,
} from "@bunyad/image";

export {
  Live,
  LiveComponent,
  registerLiveComponent,
  mountLive,
  updateLive,
  clientScript,
} from "@bunyad/live";
export type {
  LiveComponentClass,
  LiveRoutesOptions,
  Snapshot as LiveSnapshot,
  LiveCall,
  LiveUpdatePayload,
  LiveUpdateResult,
  LiveEffects,
  LiveEvent,
} from "@bunyad/live";

export {
  connectSqlite,
  connectPostgres,
  connectMysql,
  connectMariadb,
  connectSqlsrv,
  connect,
  connectFromEnv,
  configFromEnv,
  DatabaseManager,
  QueryBuilder,
  DB,
  Schema,
  migrate,
  rollback,
  fresh,
  status,
  wipe,
  Seeder,
  LengthAwarePaginator,
  Paginator,
  AbstractPaginator,
  QueryException,
  type Connection,
  type DatabaseConfig,
  type DriverName,
} from "@bunyad/database";

export {
  Notification,
  NotificationFake,
  NotificationSender,
  setNotificationSender,
  notify,
  databaseNotifications,
  MemoryDatabaseNotificationRepository,
  SqliteDatabaseNotificationRepository,
  SlackMessage,
  SmsMessage,
  VonageMessage,
  BroadcastMessage,
  ArraySlackSender,
  HttpSlackSender,
  ArraySmsSender,
  HttpSmsSender,
  type Notifiable,
  type NotificationChannel,
  type SlackSender,
  type SmsSender,
} from "@bunyad/notifications";

export {
  ShouldBroadcast,
  SyncBroadcaster,
  LogBroadcaster,
  NullBroadcaster,
  SseHub,
  SseBroadcaster,
  PusherBroadcaster,
  AblyBroadcaster,
  ChannelManager,
  PresenceStore,
  RedisPresenceStore,
  setChannelManager,
  Broadcast,
  BroadcastManager,
  AnonymousBroadcast,
  setBroadcastManager,
  getBroadcastManager,
  setPresenceStore,
  setBroadcaster,
  setSseHub,
  RedisPresenceFanout,
  RedisHubFanout,
  setPresenceFanout,
  getPresenceFanout,
  setHubFanout,
  getHubFanout,
  broadcast,
} from "@bunyad/broadcasting";

export {
  Schedule,
  ScheduledEvent,
  setSchedule,
  schedule,
  setScheduleJobRunner,
  setScheduleCommandRunner,
  setScheduleMutexStore,
  setScheduleMailSender,
  cronMatches,
  getSchedule,
} from "@bunyad/schedule";

export {
  TestClient,
  TestCase,
  test,
  testCase,
  refreshDatabase,
  assertDatabaseHas,
  assertDatabaseMissing,
  assertDatabaseCount,
  PendingCommand,
  type TestResponse,
  type TestClientOptions,
  type TestCaseOptions,
  type CreateApplicationFn,
  type RefreshDatabaseOptions,
} from "@bunyad/testing";

export { defaultCompilerPlugins } from "./plugins.ts";

export { tokenGuardUsing } from "./token-guard-using.ts";
export { ResetPassword, VerifyEmail } from "./auth-notifications.ts";

export {
  setPreloadedDiscovery,
  getPreloadedDiscovery,
  type PreloadedDiscovery,
} from "./discovery.ts";

export {
  bootFrameworkProviders,
  loadFrameworkConfig,
  registerFrameworkProviders,
  FRAMEWORK_PROVIDERS,
  type BootFrameworkOptions,
  type FrameworkProviderName,
  DatabaseServiceProvider,
  DumpServiceProvider,
  EventServiceProvider,
  ViewServiceProvider,
  CacheServiceProvider,
  FilesystemServiceProvider,
  HttpServiceProvider,
  LogServiceProvider,
  SessionServiceProvider,
  MailServiceProvider,
  QueueServiceProvider,
  NotificationServiceProvider,
  BroadcastServiceProvider,
  AuthServiceProvider,
  LiveServiceProvider,
  HeadServiceProvider,
  InertiaServiceProvider,
  FeatureServiceProvider,
  defaultDatabaseConfig,
  defaultRedisConfig,
  mysqlConnectionFromEnv,
  mariadbConnectionFromEnv,
  normalizeConnectionName,
  pgsqlConnectionFromEnv,
  sqlsrvConnectionFromEnv,
  resolveDatabaseConfig,
  resolveRedisUrl,
  standardDatabaseConnections,
  type DatabaseConnectionsConfig,
  type RedisConnectionConfig,
  type SessionConfig,
} from "./providers/index.ts";

export { installGlobals } from "./globals.ts";

// Full-stack helpers (csrf_token, bcrypt, event, …) + core globals.
import "./globals.ts";
